# Global Prometheus configuration
global:
  # Default metrics collection interval
  scrape_interval: 15s
  # Alert rules evaluation interval
  evaluation_interval: 15s
  # Add external labels to metrics
  external_labels:
    monitor: 'nestjs-app-monitor'

# Alert rules configuration (can be added later)
rule_files:
  # - "alert_rules.yml"

# Scraping configuration - where to collect metrics from
scrape_configs:
  # Collect metrics from Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s
    metrics_path: '/metrics'

  # Collect metrics from NestJS application
  # Main source of our application metrics
  - job_name: 'nestjs-app'
    static_configs:
      - targets: ['host.docker.internal:3000']  # For Docker on Mac/Windows
      # - targets: ['172.17.0.1:3000']         # For Docker on Linux
    scrape_interval: 15s
    metrics_path: '/metrics'
    scrape_timeout: 10s
    # Add labels for application identification
    relabel_configs:
      - target_label: 'app'
        replacement: 'nestjs-boilerplate'
      - target_label: 'environment'
        replacement: 'development'

  # Collect system metrics from Node Exporter
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s
    metrics_path: '/metrics'

  # Collect Docker container metrics from cAdvisor
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 30s
    metrics_path: '/metrics'

# Alertmanager configuration (for future use)
# alerting:
#   alertmanagers:
#     - static_configs:
#         - targets:
#           - alertmanager:9093